name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Build
        run: pnpm -w -r run build || true
      - name: Test
        run: pnpm -w -r run test || true

  canary-monitor:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      actions: write
    env:
      PROMETHEUS_URL: ${{ secrets.PROMETHEUS_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      RELEASE_PR_NUMBER: ${{ inputs.release_pr_number }}
      API_ADMIN_URL: ${{ secrets.API_ADMIN_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      SLO_ERROR_RATE: '0.02'
      SLO_P95_MS: '1500'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Run canary monitor
        run: pnpm canary:monitor


