name: E2E
on:
  pull_request:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Install Playwright browsers
        run: pnpm -C apps/web exec playwright install --with-deps
      - name: Start API
        run: pnpm -C services/api dev &
      - name: Wait for API
        run: npx wait-on http://localhost:4000/healthz
      - name: Start web
        run: pnpm -C apps/web dev &
      - name: Wait for web
        run: npx wait-on http://localhost:3000
      - name: Run Playwright tests
        run: pnpm -C apps/web e2e
      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            apps/web/test-results
            apps/web/playwright-report


