version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports: ["1025:1025", "8025:8025"]
  api:
    build: ../../services/api
    command: pnpm start
    ports: ["4000:4000"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/chat
      REDIS_URL: redis://redis:6379/0
      AI_BOT_URL: http://ai:4100/classify
      WEB_PUSH_VAPID_PUBLIC_KEY: ${WEB_PUSH_VAPID_PUBLIC_KEY}
      WEB_PUSH_VAPID_PRIVATE_KEY: ${WEB_PUSH_VAPID_PRIVATE_KEY}
    depends_on: [db, redis, ai]
  ai:
    build: ../../services/ai-bot
    command: pnpm start
    ports: ["4100:4100"]
  dirsync:
    build: ../../services/directory-sync
    command: pnpm start
    ports: ["4200:4200"]
  web:
    build: ../../apps/web
    command: pnpm start
    ports: ["8080:3000"]
    environment:
      NEXT_PUBLIC_API_HTTP: http://api:4000
      NEXT_PUBLIC_API_WS: http://api:4000
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${WEB_PUSH_VAPID_PUBLIC_KEY}
  admin:
    build: ../../apps/admin
    command: pnpm start
    ports: ["8081:3001"]
    environment:
      NEXTAUTH_URL: http://localhost:8081
      NEXTAUTH_SECRET: devsecret
      EMAIL_SERVER_HOST: mailhog
      EMAIL_SERVER_PORT: 1025


