global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:4000']
    metrics_path: /metrics
  - job_name: 'ai-bot'
    static_configs:
      - targets: ['ai:4100']
    metrics_path: /metrics