name: Weekly AI Eval
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Generate expanded testset (synthetic)
        run: pnpm -C services/ai-bot dlx tsx scripts/generate-testset.ts
      - name: Run offline evaluator
        run: pnpm -C packages/shared dlx tsx bin/eval-ai.ts
      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-eval-report
          path: docs/ai/reports

